Repository rstacruz/cheatsheets, pull requests merged in 2020-07, with the labels that each got.

#1486 simple typo correction
  rails-migrations.md
  rails-routes.md
Labels: size/XS

#1489 Sponsor update
  _data/berry.yml
  _data/carbon.yml
  _includes/2017/codefund.html
  _includes/2017/headline-ad.html
  _layouts/2017/home.html
  _layouts/2017/sheet.html
  _parcel/critical-home.scss
  _parcel/critical-sheet.scss
  _sass/2017/components/codefund-sponsor.scss
  _sass/2017/components/headline-ad.scss
  _sass/2017/components/main-heading.scss
  _sass/2017/components/side-ad.scss
  _sass/2017/components/site-header.scss
  _sass/2017/style.scss
  _sass/2017/utils/carbon-style.scss
Labels: size/L

#1484 Bash: add `else` example
  bash.md
Labels: size/XS

#1490 Formatting: update formatting of 20+ files
  ansi.md
  atom.md
  bookshelf-contrib.md
  cordova.md
  crypto.md
  freenode.md
  google-webfonts.md
  imagemagick.md
  jquery-cdn.md
  nodejs-assert.md
  nodejs-path.md
  package.json
  passenger.md
  premailer.md
  qunit.md
  rails-gems.md
  ruby21.md
  rubygems.md
  siege.md
  simple_form.md
  spreadsheet.md
  vim-easyalign.md
  weinre.md
  yarn.lock
  znc.md
Labels: size/XL

#1483 vim: Added '%' as a quick delimiter navigator
  vim.md
Labels: size/XS

#1482 Update resolutions.md
  resolutions.md
Labels: size/S

#1481 sass: Update sass.md
  sass.md
Labels: size/S

#1479 emmet: Fixed a typo in Emmet Cheatsheet
  emmet.md
Labels: size/XS

#1491 Style updates
  _includes/2017/headline-pub.html
  _layouts/2017/home.html
  _layouts/2017/sheet.html
  _layouts/default-ad.html
  _layouts/default.html
  _parcel/_utils.scss
  _parcel/critical-home.scss
  _parcel/critical-sheet.scss
  _sass/2015/components/post-headline.sass
  _sass/2015/style.sass
  _sass/2017/components/headline-pub.scss
  _sass/2017/components/main-heading.scss
  _sass/2017/components/site-header.scss
  _sass/2017/style.scss
  _sass/2017/utils/carbon-style.scss
  assets/style.css
Labels: size/L

#1492 Update URL for placements
  _data/carbon.yml
Labels: size/XS

#1477 httpie: Add raw JSON example
  httpie.md
Labels: size/XS

#1381 Add CREATE USER
  mysql.md
Labels: needs formatting, size/L

#984 sed: Added command for excluding lines while printing
  sed.md
Labels: size/S

#988 vimscript: Function stridx return value is an index
  vimscript-functions.md
  vimscript.md
Labels: size/S

#947 bash: Fix substring expansion with negative offset
  bash.md
Labels: bug, size/XS

#558 Flow: Fix the example for width subtyping
  flow.md
Labels: bug

#1495 Tech: fix 301 redirects
  netlify.toml
Labels: size/L

#1496 Cleanup: formatting update (2020-07-05)
  brunch.md
  c_preprocessor.md
  deku.md
  deku@1.md
  dom-range.md
  dom-selection.md
  ec2.md
  git-extras.md
  gmail.md
  promise.md
  ruby.md
  travis.md
Labels: size/XL

#1497 Add introduction sections
  _sass/2017/components/h3-section.scss
  _sass/2017/components/main-heading.scss
  bash.md
  enzyme.md
  enzyme@2.md
  factory_bot.md
  fastify.md
  go.md
  httpie.md
  sass.md
  xpath.md
Labels: size/L

#1498 Update styling
  _layouts/2017/home.html
  _layouts/2017/sheet.html
  _sass/2017/components/headline-pub.scss
  enzyme.md
  httpie.md
  promise.md
Labels: size/M

#1370 vim: Fix two minor errors
  vim.md
Labels: size/XS

#1376 Remove extra closing braces
  vue.md
Labels: size/XS

#1375 phoenix-migrations: changed precision to apply to decimal
  phoenix-migrations.md
Labels: size/XS

#1501 fix accessibility and search form
  _parcel/behaviors/search-form.js
  _parcel/helpers/search.js
  _sass/2017/base/base.scss
Labels: size/S

#1334 Update vim.md
  vim.md
Labels: size/M
