Repository rstacruz/cheatsheets, pull requests merged in 2020-06, with the labels that each got.

#1460 Remove duplicate MIT license line from Badges
  badges.md
Labels: size/XS

#1454 Update jest.md
  jest.md
Labels: size/XS

#1427 Added pm2 save
  pm2.md
Labels: size/XS

#1458 fix command First-time setup docker
  CONTRIBUTING.md
Labels: size/XS

#1451 Adding reference to whereNotIn
  knex.md
Labels: size/XS

#1443 Add brew upgrade to Global commands
  homebrew.md
Labels: size/XS

#1440 Add %tag=value query
  ledger.md
Labels: size/XS

#1437 Correction of small typing errors
  python.md
Labels: size/S

#1431 fix words section
  vim.md
Labels: size/XS

#1410 Correct bash.md to reflect `:` behaviour in parameter expansion
  bash.md
Labels: size/S

#1408 Update capybara.md - click => click_on
  capybara.md
Labels: size/XS

#1402 Update bash.md
  bash.md
Labels: size/S

#1397 Corrected conditions, removed superfluous brackets
  bash.md
Labels: size/S

#1391 css-flexbox.md
  css-flexbox.md
Labels: size/XS

#1390 Added new() to get pointer
  go.md
Labels: size/XS

#1446 Small improvement
  js-array.md
Labels: size/S

#1453 Use example.com instead of service.com
  rest-api.md
Labels: size/XS

#1438 Delete current buffer
  spacemacs.md
Labels: size/XS

#1417 findRight is actually findLast
  lodash.md
Labels: size/XS

#1380 Update curl.md
  curl.md
Labels: size/XS

#1389 Update html-meta.md
  html-meta.md
Labels: size/XS

#1383 parent directory example
  bash.md
Labels: size/S

#1374 Add --cvs-exclude flag docs
  rsync.md
Labels: size/XS

#1425 Update makefile.md
  makefile.md
Labels: size/XS

#1382 Added [:print:] class to character classes
  regexp.md
Labels: size/S

#1462 Add a way to get the last element
  bash.md
Labels: size/XS

#1421 Added inline snapshots to Jest
  jest.md
Labels: size/XS

#1472 Tech improvement: Fix CSS, and enable minification
  .github/workflows/build.yml
  .travis.yml
  Makefile
  _sass/2017/components/announcements-item.scss
  _support/smoke_test.sh
  cssnano.config.js
  netlify.toml
  package.json
  postcss.config.js
Labels: size/L

#1473 Reenable minifier, disable Travis
  .travis.yml
  _includes/meta.html
  jsdoc.md
  netlify.toml
Labels: size/L

#1476 Fix typo
  sed.md
Labels: size/XS

#813 [Lodash] Fix padding
  lodash.md
Labels: enhancement

#534 bash: expanded working with arrays
  bash.md
Labels: enhancement

#772 factory_bot: Update static attributes using dynamic
  factory_bot.md
Labels: enhancement, size/S

#971 markdown: add checkbox
  markdown.md
Labels: size/XS

#522 vim: Added system clipboard copy-paste shortcuts
  vim.md
Labels: enhancement, size/S
