Repository rstacruz/cheatsheets, pull requests merged in 2020-08, with the labels that each got.

#1509 bluebird: `Promise.prototype.finally` is standard Promise API method
  bluebird.md
Labels: size/XS

#1506 [JSDoc] Link to the full list of keywords
  jsdoc.md
Labels: size/XS

#1516 composer: Add examples of how to pass versions
  composer.md
Labels: size/S

#1514 Added more header tags & ordered lists
  markdown.md
Labels: size/S

#1199 go: Update "statements in if" use case
  go.md
Labels: size/XS

#1385 Add Slim whitespacing section
  slim.md
Labels: size/S

#1064 docker: Supply more helpful docker run -p description
  docker.md
Labels: size/XS

#1063 Add example in moment.js cheatsheet
  _includes/common/moment_format.md
Labels: size/M

#1332 go: Add documentation for golang interfaces
  go.md
Labels: size/M

#1120 tig: Add `tig -C` invocation tip
  tig.md
Labels: size/XS
