Repository rstacruz/cheatsheets, pull requests merged in 2020-02, with the labels that each got.

#1358 Updated accessing a single prop's value
  enzyme.md
Labels: size/XS

#1357 Add tmux shortcut to show pane numbers
  tmux.md
Labels: size/XS

#1356 Update moment.md
  moment.md
Labels: size/S

#1349 Update emmet.md
  emmet.md
Labels: size/XS

#1340 Update rollup.md
  rollup.md
Labels: size/S

#1339 Update go.md
  go.md
Labels: size/M

#1318 Fixed tmux attach.
  tmux.md
Labels: size/XS

#1319 Update git-branch.md
  git-branch.md
Labels: size/XS

#1368 Command to convert newlines from Windows to Unix
  vim.md
Labels: size/XS

#1367 Add bash $_ last argument of the previous command
  bash.md
Labels: size/S

#1365 Display -i, --include
  curl.md
Labels: size/XS

#1363 [YAML]: Add Reference content
  yaml.md
Labels: size/XS

#1316 Fix: Use room and remove user from gitter room link
  badges.md
Labels: size/XS

#1366 Adding command to update autoloader files
  composer.md
Labels: size/XS
