Repository rstacruz/cheatsheets, pull requests merged in 2021-12, with the labels that each got.

#1753 Wrong range for TINYINT
  mysql.md
Labels: size/XS

#1743 Fish shell page update
  fish-shell.md
Labels: size/L

#1734 Add composer outdated --direct
  composer.md
Labels: size/XS

#1731 Elixir: Add `with` Example
  elixir.md
Labels: size/S

#1729 Added iPhone 12/13, and some Galaxy details
  resolutions.md
Labels: size/M

#1757 Update bash.md
  bash.md
Labels: size/XS

#1760 Update bash.md
  bash.md
Labels: size/XS

#1764 Update fish.md (formatted from #1758)
  fish-shell.md
Labels: size/L
