Repository rstacruz/cheatsheets, pull requests merged in 2021-09, with the labels that each got.

#1704 Update Ember syntax
  ember.md
Labels: size/M

#1707 Update atom.md
  atom.md
Labels: size/M

#1708 Empty out robots.txt
  robots.txt
Labels: size/XS

#1710 Add greek characters to vim-digraphs.md
  vim-digraphs.md
Labels: size/S

#1683 fix spelling issue in Python
  python.md
Labels: size/XS

#1694 Expanded the python cheat-sheet
  python.md
Labels: size/S

#1713 Add --show-error to curl cheatsheet
  curl.md
Labels: size/XS

#1701 Update cron.md
  cron.md
Labels: size/XS

#1688 Add Jinja cheatsheet
  jinja.md
  jinja2.md
Labels: size/L

#1223 Add grep.md
  grep.md
Labels: size/L, needs formatting

#1687 Add mako cheatsheet
  mako.md
Labels: size/L

#1664 vimscript: Fix invalid code example
  vimscript.md
Labels: size/XS

#1677 Update jsdoc.md
  jsdoc.md
Labels: size/XS
