Repository rstacruz/cheatsheets, pull requests merged in 2021-01, with the labels that each got.

#1600 fix: typo
  httpie.md
Labels: size/XS

#1599 Update html-email.md
  html-email.md
Labels: size/XS

#1585 Screen
  screen.md
Labels: size/M

#1577 Updated Property lookup to reflect new docs
  stylus.md
Labels: size/S

#1576 Create stimulus_reflex.md
  stimulus-reflex.md
Labels: size/L

#1559 added port param
  scp.md
Labels: size/XS

#1575 emmet - missing item
  emmet.md
Labels: size/XS

#1601 Update homebrew.md
  homebrew.md
Labels: size/XS
