Repository rstacruz/cheatsheets, pull requests merged in 2022-10, with the labels that each got.

#1885 Update kotlin.md
  kotlin.md
Labels: size/XS

#1863 Update typescript.md
  typescript.md
Labels: size/M

#1897 bash.md: update with best practices
  bash.md
Labels: size/L

#1896 added capturing group reference term
  regexp.md
Labels: size/S
