Repository rstacruz/cheatsheets, pull requests merged in 2022-11, with the labels that each got.

#1892 Add Healthcheck cheatsheet
  docker-compose.md
Labels: size/S

#1900 Bump runtime versions (Node.js v18)
  netlify.toml
Labels: size/XS

#1901 Bump github-pages gem (v227)
  Gemfile.lock
Labels: size/M

#1839 npm: add "npm rm"
  npm.md
Labels: size/XS

#1899 grep: slashes do not need backslashes
  grep.md
Labels: size/XS

#1898 sed: fix "!p" example
  sed.md
Labels: size/XS

#1891 docker: Add depends_on long syntax
  docker-compose.md
Labels: size/S

#1536 Using latest rollup babel plugin
  rollup.md
Labels: size/XS

#1797 Update subgrid value
  css-grid.md
Labels: size/XS

#1647 update some links from http to https where supported
  _sass/2015/base/utils.sass
  ansible-modules.md
  appcache.md
  awscli.md
  capybara.md
  css-flexbox.md
  docker.md
  enzyme.md
  heroku.md
  html-microformats.md
  jekyll.md
  jest.md
  jshint.md
  lua.md
  nodejs-fs.md
  rails-migrations.md
  ronn.md
  semver.md
  travis.md
  vim-diff.md
Labels: size/L

#1623 Fix merge flag name
  gnupg.md
Labels: size/XS
