Repository rstacruz/cheatsheets, pull requests merged in 2022-12, with the labels that each got.

#1905 fix: make the meaning of ^ and $ more precise
  regexp.md
Labels: size/S

#1917 Update bash.md
  bash.md
Labels: size/XS

#1918 Update tig cheatsheet
  tig.md
Labels: size/L
