Repository rstacruz/cheatsheets, pull requests merged in 2023-03, with the labels that each got.

#1961 Refresh README: mention similar projects
  README.md
Labels: size/XS

#1953 Add Command Line Interface Pages (CLIP) page syntax examples
  clip.md
Labels: size/M

#1965 Content formatting update
  react-router.md
  riot.md
  rspec-rails.md
  rspec.md
  rst.md
  sequel.md
  sequelize.md
  sinon-chai.md
  social-images.md
  spine.md
  superagent.md
  tmux.md
  typescript.md
  ubuntu.md
  umdjs.md
  underscore-string.md
  unicode.md
  vim-digraphs.md
  vim-easyalign.md
  vim-rails.md
  vimscript-functions.md
  vimscript-snippets.md
  virtual-dom.md
  vows.md
  yargs.md
Labels: size/L

#1966 Content formatting update (part 2)
  riot.md
Labels: size/XS

#1967 Content formatting update (part 3)
  angularjs.md
  applinks.md
  bookshelf.md
  browser-sync.md
  browserify.md
  bundler.md
  divshot.md
  do.md
  emacs.md
  ember.md
  express.md
  google_analytics.md
  hledger.md
  ios-provision.md
  koa.md
  kramdown.md
  less.md
  linux.md
  machinist.md
  middleman.md
  minitest.md
  mocha.md
  modernizr.md
  nodejs-fs.md
  nodejs-process.md
  nodejs.md
  pacman.md
  perl-pie.md
  plantuml.md
  pry.md
  qjs.md
  ractive.md
  weinre.md
Labels: size/L

#1798 Remove bad negative example from capybara sheet
  capybara.md
Labels: size/XS

#1969 Content formatting update (part 5)
  angularjs.md
  ansible.md
  arel.md
  cask-index.md
  circle.md
  command_line.md
  commander.js.md
  devise.md
  elixir-metaprogramming.md
  firefox.md
  flux.md
  git-tricks.md
  gulp.md
  ledger-examples.md
  ledger-format.md
  ledger-periods.md
  ledger-query.md
  lua.md
  make-assets.md
  makefile.md
  mocha-html.md
  mocha-tdd.md
  nodejs.md
  nopt.md
  parsimmon.md
  phoenix-ecto@1.2.md
  postgresql.md
  projectionist.md
  python.md
  rails-controllers.md
  rails-forms.md
  rails-helpers.md
  rails-i18n.md
  rails-migrations.md
  rails-plugins.md
  rails-routes.md
  rails-tricks.md
  tape.md
Labels: size/L

#1970 Update Google Analytics settings
  _data/google_analytics.yml
Labels: size/XS
