Repository rstacruz/cheatsheets, pull requests merged in 2023-01, with the labels that each got.

#1930 tig: Fix traling newline in header
  tig.md
Labels: size/XS

#1932 Update gnupg.md
  gnupg.md
Labels: size/XS

#1931 go-updates: Added variables and constants additions
  go.md
Labels: size/M

#1906 Add import useState
  react.md
Labels: size/XS

#1903 Added 2 movement shortcuts
  vim.md
Labels: size/S

#1939 Added nested list items, moved image embedding with reference to own block
  markdown.md
Labels: size/XS

#1938 Include have_current_path into expectations
  capybara.md
Labels: size/XS

#1944 Removed :q! and :qa!
  vim.md
Labels: size/XS

#1948 Correct the `--include` option
  curl.md
Labels: size/XS

#1947 Added basic syntax for dictionaries and lists
  yaml.md
Labels: size/M

#1941 Alternative form of long prefix/suffix removal
  bash.md
Labels: size/XS

#1553 Add npm-version command to npm cheatsheet
  npm.md
Labels: size/XS

#1783 Update find.md
  find.md
Labels: size/XS
