Repository rstacruz/cheatsheets, pull requests merged in 2024-03, with the labels that each got.

#2115 Two changes : Correction on Fish cheatsheet & version update on Docker compose
  docker-compose.md
  docker-compose.yml
  fish-shell.md
Labels: size/M

#2111 Remove redundant syntax
  bash.md
Labels: size/XS

#2124 AppleScript handler example
  applescript.md
Labels: size/S

#2121 Fix some typos
  _data/content.yml
  _sass/vendor/modularscale/_modularscale.scss
  _sass/vendor/sanitize.css/sanitize.scss
  fish-shell.md
  goby.md
  promise.md
  regexp.md
  scp.md
  vim.md
Labels: size/M

#2122 Remove a case that is not negative examples in the capybara sheet
  capybara.md
Labels: size/S

#2125 Update Node/Ruby versions
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .node-version
  .ruby-version
  package.json
Labels: size/S

#2127 Remove auto deployment to gh-pages
  .github/workflows/deploy.yml
Labels: size/M

#2131 Remove inactive cheatsheets
  _inactive/ansible.md
  _inactive/deprecated/PHP_Kohana.ctxt
  _inactive/deprecated/Rails_2.ctxt
  _inactive/deprecated/cinema4d.md
  _inactive/deprecated/compass-sprites.md
  _inactive/deprecated/docker-osx.md
  _inactive/deprecated/eslint.md
  _inactive/deprecated/github.md
  _inactive/deprecated/jquery-mobile-events.md
  _inactive/gh.md
  _inactive/git-one-liners.md
  _inactive/gpg.md
  _inactive/homebrew-formula.md
  _inactive/ios.md
Labels: size/XL

#2096 Update kotlin.md
  kotlin.md
Labels: size/XS

#2085 Fix typo. Add second star to the beginning of jsdoc block.
  jsdoc.md
Labels: size/XS

#2092 Updated out of date link in go.md
  go.md
Labels: size/XS

#2095 Add example of `not` operator to lua.md
  lua.md
Labels: size/XS

#2080 Update pm2.md
  pm2.md
Labels: size/XS

#2042 Fix before/after with no arg
  rspec.md
Labels: size/XS
