Repository rstacruz/cheatsheets, pull requests merged in 2024-02, with the labels that each got.

#2098 Improve screen
  screen.md
Labels: size/S

#2099 Update dependencies, Ruby, Node
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/rebase.yml
  .node-version
  .ruby-version
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  netlify.toml
  yarn.lock
Labels: size/XXL

#2106 Add contains exactly and match array expectations
  rspec.md
Labels: size/XS

#2102 Adds Indirection and prefix name expansion
  bash.md
Labels: size/S

#2101 Yum cheatsheet
  yum.md
Labels: size/M

#2104 new sed commands
  sed.md
Labels: size/M
